# Generated by Django 3.2.5 on 2021-08-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_in_cents',
            field=models.IntegerField(default=0),
        ),
    ]
